version: "3"
services:
  client:
    image: prashantbist/complexclient:latest
    hostname: client
    mem_limit: 128m
  server:
    image: prashantbist/complexserver:latest
    hostname: api
    mem_limit: 128m
    environment:
      PGHOST: $PGHOST
      PGDATABASE: $PGDATABASE
      PGPORT: $PGPORT
      PGUSER: $PGUSER
      PGPASSWORD: $PGPASSWORD
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT
  worker:
    image: prashantbist/complexworker:latest
    hostname: worker
    mem_limit: 128m
    environment:
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT
  nginx:
    image: prashantbist/complexnginx:latest
    mem_limit: 128m
    hostname: nginx
    ports:
      - "3050:80"

